ShifttyMaps/Controllers/LoginController.cs
using ShifttyMaps.DataContext;
using ShifttyMaps.Models;
using ShifttyMaps.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShifttyMaps.Controllers
{
    public class LoginController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            Session["roleId"] = null;
            Session["UserId"] = null;
            Session["UserName"] = null;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Users users)
        {
            if (ModelState.IsValid)
            {
                string Password = Common.EncodePasswordToBase64(users.password);
                //string Password = users.password;
                var objUsers = db.Users.Where(a => a.email.Equals(users.email) && a.password.Equals(Password)).FirstOrDefault();
                if (objUsers != null)
                {
                    Session["roleId"] = objUsers.roleid;
                    Session["UserId"] = objUsers.userid;
                    Session["UserName"] = objUsers.firstname + " " + objUsers.lastname;
                    Session.Timeout = 540;
                    return Redirect("~/Map/Index");
                }
                else
                {
                    TempData["Error"] = "Invalid email or password!";
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Create");
        }
    }
}

ShifttyMaps/Views/Login/Index.cshtml
@model ShifttyMaps.Models.Users

@{ ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml"; }

<div class="card-group">
    <div class="card p-4">
        <div class="card-body">
            <div class="title-card">
                <h2>Login</h2>
                <small>
                    Sign In to your account
                </small>
            </div>
            @if (TempData["Success"] != null)
            {
                <div class="alert alert-success" role="alert">
                @TempData["Success"]
                </div>      
            }

            @if (TempData["Error"] != null)
            {
                <div class="alert alert-danger" role="alert">
                @TempData["Error"]
                </div>      
            }
            @using (Html.BeginForm("Index", "Login",
            new { ReturnUrl = ViewBag.ReturnUrl },
            FormMethod.Post, new { @class = "form", @id = "LoginForm" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-floating mb-3">
                            @Html.TextBoxFor(model => model.email, new { @class = "form-control", @placeholder = "name@example.com", @type = "email" })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                            <label for="floatingPassword">Email</label>
                    </div>
                    <div class="form-floating mb-3">
                            @Html.TextBoxFor(model => model.password, new { @class = "form-control", @type = "password", @placeholder = "name@example.com" })
                            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                            <label for="floatingPassword">Password</label>
                    </div>
                    <button type="submit" id="RegisterFormBtn" class="btn btn-theme btn-lg btn-block  waves-effect lg">Login</button>
             }
        </div>
    </div>
    <div class="card primary-color">
       
        <div class="card-body text-center page-single-content justify-content-center responsive-img">
            <img src="~/Images/ShiftyyLogo.png" alt="">
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script>
    (function (global) {

        if (typeof (global) === "undefined") {
            throw new Error("window is undefined");
        }

        var _hash = "!";
        var noBackPlease = function () {
            global.location.href += "#";

            // Making sure we have the fruit available for juice (^__^)
            global.setTimeout(function () {
                global.location.href += "!";
            }, 50);
        };

        global.onhashchange = function () {
            if (global.location.hash !== _hash) {
                global.location.hash = _hash;
            }
        };
        global.onload = function () {
            noBackPlease();

            // Disables backspace on page except on input fields and textarea..
            document.body.onkeydown = function (e) {
                var elm = e.target.nodeName.toLowerCase();
                if (e.which === 8 && (elm !== 'input' && elm !== 'textarea')) {
                    e.preventDefault();
                }
                // Stopping the event bubbling up the DOM tree...
                e.stopPropagation();
            };
            $('input').keydown(); 
        }
       
    })(window);

</script>